name: Batch Inference
on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 01:00 UTC daily (after feature pipeline)
  workflow_dispatch:
  workflow_run:
    workflows: ["Feature Pipeline"]
    types:
      - completed

jobs:
  generate_predictions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download features
      uses: actions/download-artifact@v2
      with:
        name: features
        path: data/features/
    
    - name: Download model
      uses: actions/download-artifact@v2
      with:
        name: models
        path: data/models/
    
    - name: Generate predictions
      run: python src/inference_pipeline/predict.py