name: Batch Inference
on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 01:00 UTC daily (after feature pipeline)
  workflow_dispatch:
  workflow_run:
    workflows: ["Model Training"]
    types:
      - completed

jobs:
  generate_predictions:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directories
      run: |
        mkdir -p data/models data/features data/predictions
    
    - name: Download features
      uses: actions/download-artifact@v4
      with:
        name: features
        path: data/features/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        merge-multiple: true
        if-no-files-found: warn
    
    - name: Download models
      uses: actions/download-artifact@v4
      with:
        name: ml-artifacts
        path: data/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        merge-multiple: true
        if-no-files-found: warn
    
    - name: Generate predictions
      run: python src/inference_pipeline/predict.py