name: Feature Pipeline
on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC daily
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  generate_features:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run feature engineering
      run: python src/feature_pipeline/feature_engineering.py
    
    - name: Upload feature artifacts  # Saves features for other workflows
      uses: actions/upload-artifact@v4
      with:
        name: features
        path: data/features/
        retention-days: 1