name: Model Training
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 UTC every Sunday
  workflow_dispatch:  # Manual trigger
  workflow_run:
    workflows: ["Feature Pipeline"]
    types:
      - completed

jobs:
  train_model:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download features  # Gets features from previous workflow
      uses: actions/download-artifact@v2
      with:
        name: features
        path: data/features/
    
    - name: Train model
      run: python src/model_pipeline/train.py
    
    - name: Upload model artifacts
      uses: actions/upload-artifact@v2
      with:
        name: models
        path: data/models/